config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [:create]
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "romain@romainr.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
    def self.evenexperience
        self.where("id % 2 = 0").reverse
    end
    
    def self.oddexperience
        self.where("id % 2 <> 0").reverse
    end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
end

app/models/skill.rb
class Skill < ApplicationRecord
    def self.majskills
      self.where("category = 'maj'")  
    end
    
    def self.minskills
      self.where("category = 'min'")  
    end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @skills = Skill.all
    @portfolios = Portfolio.all
    @experiences = Experience.all
    @contact = Contact.new(params[:contact])
    @page_title = "Home"
    @page_description = "Portfolio Home page."
    @page_keywords = "Home, Index, Romain Rouyer, Romain, Rouyer, romainr, IT, Engineer, Developer, Web, Portfolio"
  end
  
  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Contact.new
        format.html { render 'home'}
        format.js   { flash.now[:success] = @message = "Message sent successfully." }
      else
        format.html { render 'home'}
        format.js   { flash.now[:danger] = @message = "Cannot send message." }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= display_meta_tags site: 'Romain Rouyer Portfolio' %>

    
    <title>Romain Rouyer Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_contact.html.erb
<section class="bg-green" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading text-white text-uppercase sr-leftttitle-1">Contact</h2>
        <hr class="my-4 dark sr-leftttitle-2">
        <p class="mb-5 text-light sr-leftttitle-3">Have a question or want to work together?</p>
      </div>
    </div>
    <div class="row">
        <%= render 'contact_form' %>
    </div>
  </div>
</section>

app/views/pages/_contact_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/pages/_contact_form.html.erb
<%= form_for @contact, url: pages_path, remote: true, html: {class: "col-lg-6 mx-auto sr-contact-1", id: "contact_form"} do |f| %>
        <div class="form-group">
            <%= f.text_field  :name, required: true, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
            <%= f.text_field :email, required: true, class: "form-control", placeholder: "Enter email" %>
        </div>
        <div class="form-group">
            <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "form-control", 
                placeholder: "Your message"%>
        </div>
        <div class="hidden">
            <%= f.label :nickname %>
            <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
        </div>
        <div>
            <div class="col-md-10 float-left" id="flash_message">
                <%= render 'contact_flash' %>
            </div>
            <%= f.submit "Submit", class: "btn btn-sm btn-primary float-right" %>
        </div>
<% end %>

app/views/pages/_experience.html.erb
<section class="bg-white" id="experience">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-dark text-uppercase sr-righttitle-1">Experience</h2>
        <hr class="my-4 sr-righttitle-2">
        <p class="section-subheading text-muted sr-righttitle-3">Relevant work experience</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="timeline sr-experience-1">
        <% @experiences.reverse.each do |e| %>  
            <% @experiences.oddexperience.each do |i| %>
                <% if i.id == e.id %>
                  <li class="sr-experience-<%= e.id.to_s %>">
                    <div class="timeline-image">
                        <%= image_tag "experience/" + e.image, class: "rounded-circle img-fluid" %>
                    </div>
                    <div class="timeline-panel">
                      <div class="timeline-heading">
                        <h4><%= e.date %></h4>
                        <h4 class="subheading"><%= e.title %></h4>
                      </div>
                      <div class="timeline-body">
                        <p class="text-muted"><%= e.description.html_safe %></p>
                      </div>
                    </div>
                  </li>
                <% end %>
            <% end %>
            <% @experiences.evenexperience.each do |i| %>
                <% if i.id == e.id %>
                  <li class="timeline-inverted sr-experience-<%= e.id.to_s %>">
                    <div class="timeline-image">
                        <%= image_tag "experience/" + e.image, class: "rounded-circle img-fluid" %>
                    </div>
                    <div class="timeline-panel">
                      <div class="timeline-heading">
                        <h4><%= e.date %></h4>
                        <h4 class="subheading"><%= e.title %></h4>
                      </div>
                      <div class="timeline-body">
                        <p class="text-muted"><%= e.description.html_safe %></p>
                      </div>
                    </div>
                  </li>
                <% end %>
            <% end %>
         <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/pages/_footer.html.erb
<section class="bg-dark py-3 text-center" id="footer">
    <div class="container">
        <div class="row">
          <div class="col-sm-1 ml-auto">
            <%= link_to icon("fab", "github", class: "fa-3x mb-3 icon-green", title: "Github"), "https://github.com/romainr88", target: :_blank %>
          </div>
          <div class="col-sm-1 mx-1">
            <%= link_to icon("fab", "linkedin", class: "fa-3x mb-3 icon-green", title: "LinkedIn"), "https://www.linkedin.com/in/romain-rouyer-874170b9/en", target: :_blank %>
          </div>
          <div class="col-sm-1 mx-1">
            <%= link_to icon("fas", "file-alt", class: "fa-3x mb-3 icon-green", title: "Resume"), "resume.pdf", target: :_blank %>
          </div>
          <div class="col-sm-1 mr-auto">
            <%= mail_to "romain@romainr.com", icon("fas", "envelope", class: "fa-3x icon-green", title: "Contact") %>
          </div>
        </div>
    </div>
    <div class="highlight pt-3">Romain Rouyer <span class="text-light">©2020</span></div>
</section>

app/views/pages/_portfolio.html.erb
<section class="p-0 bg-dark" id="portfolio">
  <div class="container-fluid p-0">
    <div class="row no-gutters">
      <% @portfolios.each do |p| %>
        <div class="col-lg-4 col-sm-6 mx-auto sr-portfolio-<%= p.id.to_s %>">
            <%= link_to "#portfolioModal" + p.id.to_s, "data-toggle" => 'modal', class: "portfolio-box" do %>
            <%= image_tag "portfolio/thumbnails/" + p.thumb_image, class: "img-fluid" %>
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  <%= p.category %>
                </div>
                <div class="project-name">
                  <%= p.title %>
                </div>
              </div>
            </div>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/_skill.html.erb
<section class="bg-green" id="majSkills">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-white text-uppercase sr-righttitle-1">Major Skills</h2>
        <hr class="dark my-4 sr-righttitle-2">
        <p class="section-heading text-light sr-righttitle-3">+4 Years of experience</p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @skills.majskills.each do |s| %>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box mt-5 mx-auto">
            <%= icon("fas", s.icon, class: "fa-4x text-dark mb-3 sr-icon-" + s.id.to_s) %>
            <h3 class="mb-3 text-white"><%= s.title %></h3>
            <p class="text-light mb-0"><%= s.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<section class="bg-light" id="minSkills">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase sr-leftttitle-1">Minor Skills</h2>
        <hr class="my-4 sr-leftttitle-2">
        <p class="section-heading text-muted sr-leftttitle-3">~2 Years of experience</p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @skills.minskills.each do |s| %>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box mt-5 mx-auto">
            <%= icon("fas", s.icon, class: "fa-4x text-green mb-3 sr-icon-" + s.id.to_s) %>
            <h3 class="mb-3"><%= s.title %></h3>
            <p class="text-muted mb-0"><%= s.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/_skills.html.erb
<section class="bg-green" id="majSkills">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-white">At Your Service</h2>
        <hr class="dark my-4">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <%= icon('fas', 'gem', class: "fa-4x text-dark mb-3 sr-icon-1") %>
          <h3 class="mb-3 text-white">Sturdy Templates</h3>
          <p class="text-light mb-0">Our templates are updated regularly so they don't break.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
          <h3 class="mb-3">Ready to Ship</h3>
          <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fas fa-4x fa-code text-primary mb-3 sr-icon-3"></i>
          <h3 class="mb-3">Up to Date</h3>
          <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
          <h3 class="mb-3">Made with Love</h3>
          <p class="text-muted mb-0">You have to make your websites with love these days!</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="bg-light" id="minSkills">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">At Your Service</h2>
        <hr class="my-4">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <%= icon('fas', 'gem', class: "fa-4x text-green mb-3 sr-icon-1") %>
          <h3 class="mb-3">Sturdy Templates</h3>
          <p class="text-muted mb-0">Our templates are updated regularly so they don't break.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
          <h3 class="mb-3">Ready to Ship</h3>
          <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fas fa-4x fa-code text-primary mb-3 sr-icon-3"></i>
          <h3 class="mb-3">Up to Date</h3>
          <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
          <h3 class="mb-3">Made with Love</h3>
          <p class="text-muted mb-0">You have to make your websites with love these days!</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact_form').html("<%= j render 'contact_form' %>");
$('#flash_message').html("<%= j render 'contact_flash' %>").delay(3000).fadeOut(4000);

app/views/pages/home.html.erb
<header class="masthead text-center text-white d-flex">
    <%= video_tag(
      'code.mp4',
      id: 'background',
      autoplay: true,
      loop: true,
      muted: true
    )
    %>
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <div id="typed-strings">
          <p>Hello, I'm <span class="highlight">Romain Rouyer</span>.
           <br>
           I'm a passionate IT Engineer with 5 years’ experience in various IT fields.
           <br>
           Currently living in France.
	  </p>
        </div>
        <span class="text" id="typed"></span>
        <hr>
      </div>
      <div class="col-lg-8 mx-auto">
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#majSkills">About Me</a>
      </div>
    </div>
  </div>
</header>

<%= render "skill" %>
<%= render "portfolio" %>
<%= render "experience" %>
<%-# <%= render "contact" -%>
<%= render "footer" %>
<%= render "shared/modal" %>

app/views/shared/_modal.html.erb
<% @portfolios.each do |p| %>
    <div class="portfolio-modal modal fade" id="portfolioModal<%= p.id.to_s %>" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="row">
                    <button type="button" class="close mr-1 text-right" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="row">
                    <h4 class="modal-title col text-center" id="exampleModalLabel"><%= p.title %></h4>
                </div>
                <hr>
            </div>
            <div class="container">
            <div class="row">
              <div class="col-lg-12 mx-auto">
                <div class="modal-body text-center">
                  <%= link_to image_tag("portfolio/fullsize/" + p.full_image, class: "img-fluid"), p.website, target: :_blank %>
                  <h5 class="mt-3 text-muted">Features:</h5>
                  <p><%= p.description.html_safe %></p>
                  <h5 class="mt-3 text-muted">Language and Framework utilised:</h5>
                  <div class="text-left">
                    <% @portfolios.find(p.id).technologies.each do |t| %>
                      <%= image_tag("logo/" + t.logo, class: "logo mx-1", title: t.name) %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
            <div class="modal-footer text-center">
                <a class="btn btn-primary btn-sm" href="<%= p.website %>" target="_blank">View Website</a>
                <a class="btn btn-primary btn-sm" data-dismiss="modal">Close</a>
            </div>
        </div>
      </div>
    </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">Home</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#majSkills">Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#footer">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>